/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.angile.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.angile.Service.AuhorServicesImpl;
import com.angile.model.TbAuthor;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Tuan Khai
 */
@SuppressWarnings("all")
public class AuthorManager extends javax.swing.JFrame {

	/**
	 * Creates new form AuthorManager
	 */
	DefaultTableModel tableModel = new DefaultTableModel();
	AuhorServicesImpl auhorServicesImpl = new AuhorServicesImpl();
	private int flag = 0;

	public AuthorManager() {
		initComponents();
		initFrame();
		showDataTableAuthor();
	}

	void initFrame() {
		swithEmnable(false);
		btnEdit.setEnabled(false);
		btnBoqua.setEnabled(false);
		btnSave.setEnabled(false);
		btnDelete.setEnabled(false);

	}

	void swithEmnable(boolean dieukien) {
		tfCodeAuthor.setEnabled(false);
		tfNameAuthor.setEnabled(dieukien);
		tfAddressAuthor.setEnabled(dieukien);
		tfEmailAuthor.setEnabled(dieukien);
		tfPhoneAuthor.setEnabled(dieukien);
	}

	void showDataTableAuthor() {
		tableModel = (DefaultTableModel) tblAuthor.getModel();
		tableModel.setRowCount(0);
		for (TbAuthor x : auhorServicesImpl.getAuthor(0, 10)) {
			tableModel.addRow(new Object[] { x.getId(), x.getNameAuthor(), x.getPhoneAuthor(), x.getAddressAuthor(),
					x.getEmailAuthor() });

		}
	}

	void clearForm() {
		tfCodeAuthor.setText(null);
		tfNameAuthor.setText(null);
		tfAddressAuthor.setText(null);
		tfEmailAuthor.setText(null);
		tfPhoneAuthor.setText(null);
	}

	void showAuthorById(int id) {
		TbAuthor author = auhorServicesImpl.getAuthorById(id);
		tfCodeAuthor.setText(author.getId() + "");
		tfNameAuthor.setText(author.getNameAuthor());
		tfAddressAuthor.setText(author.getAddressAuthor());
		tfEmailAuthor.setText(author.getEmailAuthor());
		tfPhoneAuthor.setText(author.getPhoneAuthor());
	}

	void deleteAuthor(int id) {
		if (auhorServicesImpl.removeAuthor(id) == true) {
			JOptionPane.showMessageDialog(null, "Xóa Thành Công");
			showDataTableAuthor();
		} else {
			JOptionPane.showMessageDialog(null, "Lỗi trong quá trình xóa");
		}
	}
	boolean validateForm() 
	{
		if (tfNameAuthor.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên");
			return false;
		} else if (tfPhoneAuthor.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Bạn chưa nhập số điện thoại");
			return false;
		} else if (tfEmailAuthor.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Bạn chưa nhập email");
			return false;
		} else if (tfAddressAuthor.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Bạn chưa nhập địa chỉ");
			return false;
		}else
		{
			return true;
		}
	}

	void addAuthor(TbAuthor author) {
		if(validateForm() == true)
		{
			if (auhorServicesImpl.addAuthor(author) == true) {
				JOptionPane.showMessageDialog(null, "Thêm tác giả thành công");
				showDataTableAuthor();
				clearForm();
			} else {
				JOptionPane.showMessageDialog(null, "Lỗi trong quá trình thêm");
			}
		}else
		{
			// To Do Code
		}
	}

	TbAuthor getAuthorFromForm() 
	{
		TbAuthor tbAuthor = new TbAuthor(tfNameAuthor.getText(), tfEmailAuthor.getText(), tfPhoneAuthor.getText(),
				tfEmailAuthor.getText());

		return tbAuthor;
	}
	void updateAuthor(TbAuthor author)
	{
		if(validateForm() == true)
		{
			if(auhorServicesImpl.editAuthor((int)tblAuthor.getValueAt(tblAuthor.getSelectedRow(), 0), author)==true)
			{
				JOptionPane.showMessageDialog(null,"Cập nhập tác giả thành công");
				showDataTableAuthor();
				initFrame();
			}else
			{
				JOptionPane.showMessageDialog(null, "Lỗi trong quá trình cập nhập");
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	/**
	 * 
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		tfCodeAuthor = new javax.swing.JTextField();
		tfNameAuthor = new javax.swing.JTextField();
		tfPhoneAuthor = new javax.swing.JTextField();
		tfAddressAuthor = new javax.swing.JTextField();
		tfEmailAuthor = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		btnEdit = new javax.swing.JButton();
		btnEdit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				swithEmnable(true);
				btnBoqua.setEnabled(true);
				btnSave.setEnabled(true);
				flag = 2;
			}
		});
		btnExport = new javax.swing.JButton();
		btnExport.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if(JOptionPane.showConfirmDialog(null, "Bạn có muốn xuất báo cáo")==0)
				{
					if(auhorServicesImpl.exportExcel()==true)
					{
						System.out.println("Xuất thành công");
					}else
					{
						System.out.println("Lỗi trong quá trình xuất file");
					}
				}
		
			}
		});
		btnBoqua = new javax.swing.JButton();
		btnBoqua.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (flag == 1) {
					swithEmnable(false);
					btnSave.setEnabled(false);
					btnBoqua.setEnabled(false);
				} else if (flag == 2) {
					swithEmnable(false);
					btnSave.setEnabled(false);
					btnBoqua.setEnabled(false);

				}
			}
		});
		btnDelete = new javax.swing.JButton();
		btnDelete.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (JOptionPane.showConfirmDialog(null, "Ban có muốn xóa không ?") == 0) {
					deleteAuthor((Integer) tblAuthor.getValueAt(tblAuthor.getSelectedRow(), 0));

				}
			}
		});
		btnAdd = new javax.swing.JButton();
		btnAdd.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				swithEmnable(true);
				clearForm();
				btnSave.setEnabled(true);
				btnBoqua.setEnabled(true);
				btnEdit.setEnabled(false);
				btnDelete.setEnabled(false);
				flag = 1;
			}
		});
		btnSave = new javax.swing.JButton();
		btnSave.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if(flag ==1)
				{
					addAuthor(getAuthorFromForm());
				}else if(flag == 2 )
				{
					updateAuthor(getAuthorFromForm());
				}
			}
		});
		jScrollPane1 = new javax.swing.JScrollPane();
		tblAuthor = new javax.swing.JTable();
		tblAuthor.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				showAuthorById((Integer) tblAuthor.getValueAt(tblAuthor.getSelectedRow(), 0));
				swithEmnable(false);
				btnEdit.setEnabled(true);
				btnDelete.setEnabled(true);
				btnSave.setEnabled(false);
				btnBoqua.setEnabled(false);

			}
		});
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Quản Lý Tác Giả");

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel1.setText("Quản Lý Tác Gỉa");

		jLabel2.setText("Mã Tác Giả");

		jLabel3.setText("Tên Tác Giả");

		jLabel4.setText("Số Điện Thoại");

		jLabel5.setText("Địa Chỉ");

		jLabel6.setText("Email");

		jLabel7.setText("Tìm Kiếm");

		jButton1.setText("Tìm Kiếm");

		btnEdit.setText("Sửa");

		btnExport.setText("Kết Xuất");

		btnBoqua.setText("Bỏ Qua");

		btnDelete.setText("Xóa");

		btnAdd.setText("Thêm");

		btnSave.setText("Lưu");

		tblAuthor.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null }, { null, null, null, null, null },
						{ null, null, null, null, null }, { null, null, null, null, null } },
				new String[] { "Mã Tác Giả", "Tên Tác Giả", "Số DT", "Địa Chỉ", "Email" }));
		jScrollPane1.setViewportView(tblAuthor);

		jMenu1.setText("Chức Năng");
		jMenu1.setToolTipText("");

		jMenuItem1.setText("Quản Lý Sách");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("Quản Lý Nhà Xuất Bản");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem3.setText("Quản Lý Chủ Đề");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem3);

		jMenuItem4.setText("Thống Kê");
		jMenu1.add(jMenuItem4);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Đăng Xuất");
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(34, 34, 34).addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel4)
												.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
										.addComponent(jLabel7))
								.addGap(34, 34, 34)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(tfAddressAuthor,
														javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(tfPhoneAuthor, javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(tfEmailAuthor, javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
														layout.createSequentialGroup().addGap(66, 66, 66)
																.addComponent(jLabel1))
												.addComponent(tfNameAuthor, javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE,
																274, Short.MAX_VALUE)
														.addGap(18, 18, 18).addComponent(jButton1)))
										.addComponent(tfCodeAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 379,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16,
										Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(btnBoqua, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(btnExport))))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGap(8, 8, 8)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(tfCodeAuthor, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnAdd))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(tfNameAuthor, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnEdit))
				.addGap(13, 13, 13)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(tfPhoneAuthor, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnDelete))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(tfAddressAuthor, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel5).addComponent(btnSave))
				.addGap(17, 17, 17)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(tfEmailAuthor, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel6).addComponent(btnBoqua))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel7)
						.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1).addComponent(btnExport))
				.addGap(31, 31, 31).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(19, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		this.setVisible(false);
		BookManager bookManager = new BookManager();
		bookManager.setVisible(true);
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
		this.setVisible(false);
		PublishingManager publishingManager = new PublishingManager();
		publishingManager.setVisible(true);
	}// GEN-LAST:event_jMenuItem2ActionPerformed

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
		// TODO add your handling code here:
		this.setVisible(false);
		ThemeManager themeManager = new ThemeManager();
		themeManager.setVisible(true);
	}// GEN-LAST:event_jMenuItem3ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AuthorManager.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AuthorManager.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AuthorManager.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AuthorManager.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AuthorManager().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton btnEdit;
	private javax.swing.JButton btnExport;
	private javax.swing.JButton btnBoqua;
	private javax.swing.JButton btnDelete;
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnSave;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTable tblAuthor;
	private javax.swing.JTextField tfAddressAuthor;
	private javax.swing.JTextField tfCodeAuthor;
	private javax.swing.JTextField tfEmailAuthor;
	private javax.swing.JTextField tfNameAuthor;
	private javax.swing.JTextField tfPhoneAuthor;
	// End of variables declaration//GEN-END:variables
}
