/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.angile.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.angile.Service.PublishingServicesimpl;
import com.angile.model.TbPlublishing;

import javassist.expr.NewArray;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Tuan Khai
 */
@SuppressWarnings("all")
public class PublishingManager extends javax.swing.JFrame {

	/**
	 * Creates new form PublishingManager
	 */
	private int flag = 0;
	private PublishingServicesimpl publishingServicesimpl = new PublishingServicesimpl();
	DefaultTableModel model = new DefaultTableModel();

	public PublishingManager() {
		initComponents();
		showDataInTablePlublishing();
		initFrame();
	}

	void initFrame() {
		swithEnabled(false);
		btnEdit.setEnabled(false);
		btnBoQua.setEnabled(false);
		btnSave.setEnabled(false);
		btnDelete.setEnabled(false);
	}

	void showDataInTablePlublishing() {
		model = (DefaultTableModel) tblPublishing.getModel();
		model.setRowCount(0);
		for (TbPlublishing x : publishingServicesimpl.getPublishing(0, 100)) {
			model.addRow(new Object[] { x.getId(), x.getNamePublishing(), x.getPhonePublishing(),
					x.getAddressPublishing(), x.getEmailPublishing() });
		}
	}

	void swithEnabled(boolean dieukien) {
		tfCodePublishing.setEnabled(false);
		tfNamePublishing.setEnabled(dieukien);
		tfPhonePublishing.setEnabled(dieukien);
		tfAddressPublishing.setEnabled(dieukien);
		tfEmailPublishing.setEnabled(dieukien);
	}

	void clearForm() {
		tfCodePublishing.setText(null);
		tfNamePublishing.setText(null);
		tfPhonePublishing.setText(null);
		tfAddressPublishing.setText(null);
		tfEmailPublishing.setText(null);
	}

	TbPlublishing getPlublishingFromForm() {
		TbPlublishing plublishing = new TbPlublishing(tfNamePublishing.getText(), tfPhonePublishing.getText(),
				tfAddressPublishing.getText(), tfEmailPublishing.getText());
		return plublishing;
	}

	boolean validateForm() {
		if (tfNamePublishing.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên");
			return false;
		} else if (tfAddressPublishing.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Bạn chưa nhập địa chỉ");
			return false;
		} else if (tfPhonePublishing.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Bạn chưa nhập số điện thoại");
			return false;
		} else if (tfEmailPublishing.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Bạn chưa nhập email");
			return false;
		} else {
			return true;
		}
	}

	void addPlublishing(TbPlublishing plublishing) {
		if (publishingServicesimpl.addPublishing(plublishing) == true) {
			JOptionPane.showMessageDialog(null, "Thêm thành công");
			showDataInTablePlublishing();
			clearForm();

		} else {
			JOptionPane.showMessageDialog(null, "Lỗi trong quá trình thêm");
		}
	}

	void updatePlublishing(int id_plublishing, TbPlublishing plublishing) {
		if (publishingServicesimpl.editPublishing(id_plublishing, plublishing) == true) {
			JOptionPane.showMessageDialog(null, "Cập nhập thành công");
			initFrame();
			showDataInTablePlublishing();
		} else {
			JOptionPane.showMessageDialog(null, "Lỗi trong quá trình cập nhập");
		}
	}

	void deletePlublishing(int id_Publishing) {
		if (publishingServicesimpl.removePublishing(id_Publishing) == true) {
			JOptionPane.showMessageDialog(null, "Xóa NBX thành công");
			showDataInTablePlublishing();
			initFrame();
		} else {
			JOptionPane.showMessageDialog(null, "Lỗi trong quá trình xóa");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		tfCodePublishing = new javax.swing.JTextField();
		tfNamePublishing = new javax.swing.JTextField();
		tfPhonePublishing = new javax.swing.JTextField();
		tfAddressPublishing = new javax.swing.JTextField();
		tfEmailPublishing = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		tfSearchPublishing = new javax.swing.JTextField();
		btnSearch = new javax.swing.JButton();
		btnExcel = new javax.swing.JButton();
		btnExcel.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				publishingServicesimpl.exportExcel();
			}
		});
		btnEdit = new javax.swing.JButton();
		btnEdit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				swithEnabled(true);
				btnBoQua.setEnabled(true);
				btnSave.setEnabled(true);
				flag = 2;
			}
		});
		btnDelete = new javax.swing.JButton();
		btnDelete.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa") == 0) {
					deletePlublishing((Integer) tblPublishing.getValueAt(tblPublishing.getSelectedRow(), 0));
				}
			}
		});
		btnSave = new javax.swing.JButton();
		btnSave.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (flag == 1) {
					if (validateForm() == true) {
						addPlublishing(getPlublishingFromForm());
					}
				} else if (flag == 2) {
					if (validateForm() == true) {
						updatePlublishing((Integer) tblPublishing.getValueAt(tblPublishing.getSelectedRow(), 0),
								getPlublishingFromForm());
					}

				}
			}
		});
		btnBoQua = new javax.swing.JButton();
		btnBoQua.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (flag == 1) {
					swithEnabled(false);
					btnSave.setEnabled(false);
					btnBoQua.setEnabled(false);
				} else if (flag == 2) {
					swithEnabled(false);
					btnSave.setEnabled(false);
					btnBoQua.setEnabled(false);

				}
			}
		});
		btnAdd = new javax.swing.JButton();
		btnAdd.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				swithEnabled(true);
				clearForm();
				btnSave.setEnabled(true);
				btnBoQua.setEnabled(true);
				btnEdit.setEnabled(false);
				btnDelete.setEnabled(false);
				flag = 1;
			}
		});
		jScrollPane1 = new javax.swing.JScrollPane();
		tblPublishing = new javax.swing.JTable();
		tblPublishing.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				getThemeById((Integer) tblPublishing.getValueAt(tblPublishing.getSelectedRow(), 0));
				swithEnabled(false);
				btnEdit.setEnabled(true);
				btnDelete.setEnabled(true);
				btnSave.setEnabled(false);
				btnBoQua.setEnabled(false);
			}

			private void getThemeById(Integer id_plublishing) {
				TbPlublishing plublishing = publishingServicesimpl.getPublishingById(id_plublishing);
				tfCodePublishing.setText(plublishing.getId() + "");
				tfNamePublishing.setText(plublishing.getNamePublishing());
				tfPhonePublishing.setText(plublishing.getPhonePublishing());
				tfAddressPublishing.setText(plublishing.getAddressPublishing());
				tfEmailPublishing.setText(plublishing.getEmailPublishing());

			}
		});
		jMenuBar2 = new javax.swing.JMenuBar();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();

		jMenu1.setText("File");
		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");
		jMenuBar1.add(jMenu2);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel1.setText("Quản Lý Nhà Xuất Bản");

		jLabel2.setText("Mã Nhà Xuất Bản");

		jLabel3.setText("Tên Nhà Xuất Bản");

		jLabel4.setText("Số Điện Thoại");

		jLabel5.setText("Địa Chỉ");

		jLabel6.setText("Email");

		tfPhonePublishing.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tfPhonePublishingActionPerformed(evt);
			}
		});

		tfAddressPublishing.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tfAddressPublishingActionPerformed(evt);
			}
		});

		jLabel7.setText("Tìm Kiếm");

		btnSearch.setText("Tìm Kiếm");

		btnExcel.setText("Kiết Xuất");

		btnEdit.setText("Sửa");

		btnDelete.setText("Xóa");

		btnSave.setText("Lưu");

		btnBoQua.setText("Bỏ Qua");

		btnAdd.setText("Thêm");

		tblPublishing.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null }, { null, null, null, null, null },
						{ null, null, null, null, null }, { null, null, null, null, null } },
				new String[] { "Mã Nhà Xuất Bản", "Tên NXB", "Số DT", "Địa Chỉ", "Email" }));
		jScrollPane1.setViewportView(tblPublishing);

		jMenu3.setText("Chức Năng");

		jMenuItem1.setText("Quản Lý Sách");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem1);

		jMenuItem2.setText("Quản Lý Chủ Đề");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem2);

		jMenuItem3.setText("Quản Lý Tác Giả");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem3);

		jMenuItem4.setText("Thống Kê");
		jMenu3.add(jMenuItem4);

		jMenuBar2.add(jMenu3);

		jMenu4.setText("Đăng Xuất");
		jMenuBar2.add(jMenu4);

		setJMenuBar(jMenuBar2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(
												jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650,
												Short.MAX_VALUE))
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
												.createSequentialGroup().addGroup(layout.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup().addGap(27, 27, 27)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel2).addComponent(jLabel4)
																		.addComponent(jLabel5).addComponent(jLabel6)
																		.addComponent(jLabel7))
																.addGap(5, 5, 5))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING, layout
																		.createSequentialGroup().addContainerGap()
																		.addComponent(jLabel3)))
												.addGap(26, 26, 26)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
																.createSequentialGroup()
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				tfPhonePublishing,
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(tfNamePublishing))
																.addGap(18, 18, 18))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
																.createSequentialGroup()
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(tfAddressPublishing,
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(tfEmailPublishing,
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				layout.createSequentialGroup()
																						.addComponent(
																								tfSearchPublishing)
																						.addGap(18, 18, 18)
																						.addComponent(btnSearch))
																		.addComponent(
																				tfCodePublishing,
																				javax.swing.GroupLayout.Alignment.LEADING))
																.addGap(16, 16, 16)))
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(btnBoQua,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(btnSave,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
														.addGroup(layout.createSequentialGroup().addGap(2, 2, 2)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																		.addComponent(btnAdd,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(btnExcel))))))
								.addGap(21, 21, 21))
				.addGroup(layout.createSequentialGroup().addGap(228, 228, 228).addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap().addComponent(jLabel1)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout
						.createSequentialGroup().addComponent(jLabel5).addGap(24, 24, 24)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel6)
								.addComponent(tfEmailPublishing, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(20, 20, 20)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel7).addComponent(tfSearchPublishing,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(40, 40, 40)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnEdit)
												.addComponent(tfNamePublishing, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnDelete)
												.addComponent(tfPhonePublishing, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnSave).addComponent(tfAddressPublishing,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18).addComponent(btnBoQua).addGap(17, 17, 17)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnExcel).addComponent(btnSearch)))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btnAdd)
										.addComponent(tfCodePublishing, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2))))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(50, 50, 50)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void tfPhonePublishingActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfPhonePublishingActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_tfPhonePublishingActionPerformed

	private void tfAddressPublishingActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfAddressPublishingActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_tfAddressPublishingActionPerformed

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		this.setVisible(false);
		BookManager bookManager = new BookManager();
		bookManager.setVisible(true);
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
		this.setVisible(false);
		ThemeManager themeManager = new ThemeManager();
		themeManager.setVisible(true);
	}// GEN-LAST:event_jMenuItem2ActionPerformed

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
		this.setVisible(false);
		AuthorManager authorManager = new AuthorManager();
		authorManager.setVisible(true);
	}// GEN-LAST:event_jMenuItem3ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PublishingManager.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PublishingManager.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PublishingManager.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PublishingManager.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PublishingManager().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSearch;
	private javax.swing.JButton btnExcel;
	private javax.swing.JButton btnEdit;
	private javax.swing.JButton btnDelete;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton btnBoQua;
	private javax.swing.JButton btnAdd;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuBar jMenuBar2;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tblPublishing;
	private javax.swing.JTextField tfAddressPublishing;
	private javax.swing.JTextField tfCodePublishing;
	private javax.swing.JTextField tfEmailPublishing;
	private javax.swing.JTextField tfNamePublishing;
	private javax.swing.JTextField tfPhonePublishing;
	private javax.swing.JTextField tfSearchPublishing;
	// End of variables declaration//GEN-END:variables
}
