/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.angile.view;

import javax.swing.table.DefaultTableModel;

import com.angile.Service.ThemeServicesImpl;
import com.angile.model.TbTheme;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Tuan Khai
 */
@SuppressWarnings("all")
public class ThemeManager extends javax.swing.JFrame {

	/**
	 * Creates new form AuthorManager
	 */
	DefaultTableModel model = new DefaultTableModel();
	ThemeServicesImpl themeServicesImpl = new ThemeServicesImpl();
	private int flag = 0;

	public ThemeManager() {
		initComponents();
		initFrame();
		showDataIntoTableTheme();
	}

	void initFrame() {
		tfCodeTheme.setEnabled(false);
		tfNameTheme.setEnabled(false);
		btnEdit.setEnabled(false);
		btnBoqua.setEnabled(false);
		btnSave.setEnabled(false);
		btnDelete.setEnabled(false);

	}

	void showDataIntoTableTheme() {
		model = (DefaultTableModel) tblTheme.getModel();
		model.setRowCount(0);
		for (TbTheme x : themeServicesImpl.getTheme(0, 10)) {
			model.addRow(new Object[] { x.getId(), x.getNameTheme() });

		}
	}

	void getThemeById(int id_theme) {
		TbTheme theme = themeServicesImpl.showThemeById(id_theme);
		tfCodeTheme.setText(theme.getId() + "");
		tfNameTheme.setText(theme.getNameTheme());

	}

	void clearForm() {
		tfCodeTheme.setText(null);
		tfNameTheme.setText(null);
	}

	void switchEmnable(boolean dieukien) {
		tfNameTheme.setEnabled(dieukien);
	}

	String addTheme() {
		String result = null;
		if (tfNameTheme.getText().equals("")) {
			result = "Tên không được rỗng";
		} else {
			if(themeServicesImpl.addTheme(tfNameTheme.getText())==true) {
				showDataIntoTableTheme();
				clearForm();
				result = "Thêm Chủ Đề Thành Công";	
			}else {
				result="Lỗi trong quá trình thêm";
			}
			
		}
		return result;
	}
	String updateTheme()
	{
		String reString = null;
		if(tfNameTheme.getText().equals("")) {
			reString = "Tên không được rỗng";
		}else{
			if(themeServicesImpl.editTheme((Integer)tblTheme.getValueAt(tblTheme.getSelectedRow(), 0),tfNameTheme.getText())==true) {
			showDataIntoTableTheme();
			reString = "Cập Nhập thành công";
			}else {
				reString="Lỗi trong quá trình cập nhập";
			}
			
		}
		return reString;
	}
	String deleteTheme(int id_theme)
	{
		String result = null;
		if(themeServicesImpl.removeTheme(id_theme)) {
			result="Xóa Thành Công";
			showDataIntoTableTheme();
		}else {
			result="Lỗi trong quá trình xóa";
		}
		return result;
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton6 = new javax.swing.JButton();
		btnAdd = new javax.swing.JButton();
		btnEdit = new javax.swing.JButton();
		btnEdit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				switchEmnable(true);
				btnBoqua.setEnabled(true);
				btnSave.setEnabled(true);
				flag = 2;
			}
		});
		btnDelete = new javax.swing.JButton();
		btnDelete.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if(JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không")==0) {
					JOptionPane.showMessageDialog(null,deleteTheme((Integer) tblTheme.getValueAt(tblTheme.getSelectedRow(), 0)));	
				}
				
			}
		});
		btnBoqua = new javax.swing.JButton();
		btnBoqua.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (flag == 1) {
					switchEmnable(false);
					btnSave.setEnabled(false);
					btnBoqua.setEnabled(false);
				} else if (flag == 2) {
					switchEmnable(false);
					btnSave.setEnabled(false);
					btnBoqua.setEnabled(false);

				}
			}
		});
		btnSave = new javax.swing.JButton();
		btnSave.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (flag == 1) {
					JOptionPane.showMessageDialog(null, addTheme());

				}else if(flag==2) {
					JOptionPane.showMessageDialog(null,updateTheme());
					
					
				}

			}
		});
		btnExport = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		tfCodeTheme = new javax.swing.JTextField();
		tfNameTheme = new javax.swing.JTextField();
		tfSearchTheme = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblTheme = new javax.swing.JTable();
		tblTheme.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				getThemeById((Integer) tblTheme.getValueAt(tblTheme.getSelectedRow(), 0));
				tfNameTheme.setEnabled(false);
				btnEdit.setEnabled(true);
				btnDelete.setEnabled(true);
				btnSave.setEnabled(false);
				btnBoqua.setEnabled(false);
			}
		});
		btnSearch = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem2.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
			}
		});
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem3.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
			}
		});
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();

		jButton6.setText("jButton6");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Quản Lý Chủ Đề");

		btnAdd.setText("Thêm");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		btnEdit.setText("Sửa");

		btnDelete.setText("Xóa");

		btnBoqua.setText("Bỏ Qua");

		btnSave.setText("Lưu");

		btnExport.setText("Kiết Xuất");
		btnExport.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jLabel1.setText("Mã Chủ Đề");

		jLabel2.setText("Tên Chủ Đề");

		jLabel3.setText("Tìm Kiếm");

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel4.setText("Quản Lý Chủ Đề");

		tblTheme.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null } },
				new String[] { "ID", "Tên Chủ Đề" }));
		jScrollPane1.setViewportView(tblTheme);

		btnSearch.setText("Tìm Kiếm");

		jMenu1.setText("Chức Năng");

		jMenuItem1.setText("Quản Lý Sách");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("Quản Lý Chủ Đề");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem3.setText("Quản Lý Tác Giả");
		jMenu1.add(jMenuItem3);

		jMenuItem4.setText("Quản Lý Độc Giả");
		jMenu1.add(jMenuItem4);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Đăng Xuất");
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(159, 159, 159))
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(btnBoqua, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 83,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnExport, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 83,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
								.addGap(23, 23, 23)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel1).addComponent(jLabel2).addComponent(jLabel3))
								.addGap(36, 36, 36)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(tfCodeTheme).addComponent(tfNameTheme)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
												.createSequentialGroup()
												.addComponent(tfSearchTheme, javax.swing.GroupLayout.PREFERRED_SIZE,
														236, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(btnSearch).addGap(1, 1, 1)))
								.addGap(28, 28, 28)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(19, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel4).addGap(25, 25, 25)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(tfCodeTheme, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnAdd))
						.addGap(23, 23, 23)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(tfNameTheme, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnEdit))
						.addGap(26, 26, 26)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(tfSearchTheme, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnDelete).addComponent(btnSearch))
										.addGap(27, 27, 27).addComponent(jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE, 252,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addGap(43, 43, 43).addComponent(btnSave)
										.addGap(18, 18, 18).addComponent(btnBoqua).addGap(18, 18, 18)
										.addComponent(btnExport)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		this.setVisible(false);
		BookManager bookManager = new BookManager();
		bookManager.setVisible(true);

	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
		// TODO add your handling code here:
		this.setVisible(false);
		ThemeManager themeManager = new ThemeManager();
		themeManager.setVisible(true);

	}// GEN-LAST:event_jMenuItem2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		switchEmnable(true);
		clearForm();
		btnSave.setEnabled(true);
		btnBoqua.setEnabled(true);
		btnEdit.setEnabled(false);
		btnDelete.setEnabled(false);
		flag = 1;
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton7ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ThemeManager.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ThemeManager.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ThemeManager.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ThemeManager.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ThemeManager().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnEdit;
	private javax.swing.JButton btnDelete;
	private javax.swing.JButton btnBoqua;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton btnExport;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tblTheme;
	private javax.swing.JTextField tfCodeTheme;
	private javax.swing.JTextField tfNameTheme;
	private javax.swing.JTextField tfSearchTheme;
	private JButton btnSearch;
	// End of variables declaration//GEN-END:variables
}
